
language: bash

services:
        - docker

before_install:
        - make prepare
        - make build

script:
        - make test


notifications:
        email:
                on_success: never
