
language: bash

services:
        - docker

before_install:
        - make prepare
        - make build

script:
        - make test

after_success:
        - make tag

notifications:
        email:
                on_success: never
