VERSION := 5.3
BUILDARG_VERSION := --build-arg VERSION=$(VERSION)
IMAGENAME := docker.io/silviof/docker-languagetool
BUILDARG_PLATFORM := --platform linux/amd64,linux/arm64/v8
NGRAM_DE := https://languagetool.org/download/ngram-data/ngrams-de-20150819.zip
NGRAM_EN := https://languagetool.org/download/ngram-data/ngrams-en-20150817.zip
FASTTEXTMODEL:=https://dl.fbaipublicfiles.com/fasttext/supervised-models/lid.176.bin

