VERSION := 6.2
UBUNTU_VERSION := --build-arg UBUNTU_VERSION=latest
BUILDARG_VERSION := --build-arg LTVersion=$(VERSION)
IMAGENAME := pei/docker-languagetool
BUILDARG_PLATFORM := --platform linux/amd64
NGRAM_URL_DE_ORG := https://languagetool.org/download/ngram-data/ngrams-de-20150819.zip
NGRAM_URL_EN_ORG := https://languagetool.org/download/ngram-data/ngrams-en-20150817.zip
NGRAM_URL_DE_LOCAL := http://172.29.240.1:5050/NGRAM_DE.zip
NGRAM_URL_EN_LOCAL := http://172.29.240.1:5050/NGRAM_EN.zip
FASTTEXTMODEL_URL:=https://dl.fbaipublicfiles.com/fasttext/supervised-models/lid.176.bin

