VERSION := 5.5
BUILDARG_VERSION := --build-arg VERSION=$(VERSION)
IMAGENAME := pei/docker-languagetool
BUILDARG_PLATFORM := --platform linux/amd64,linux/arm64/v8
NGRAM_URL_DE_ORG := https://languagetool.org/download/ngram-data/ngrams-de-20150819.zip
NGRAM_URL_EN_ORG := https://languagetool.org/download/ngram-data/ngrams-en-20150817.zip
NGRAM_URL_DE := http://172.29.240.1:5050/NGRAM_DE.zip
NGRAM_URL_EN := http://172.29.240.1:5050/NGRAM_EN.zip
FASTTEXTMODEL_URL:=https://dl.fbaipublicfiles.com/fasttext/supervised-models/lid.176.bin

