
name: Release for silvio/docker-languagetool

on:
  push:
    tags:
      - '[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+-update[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-update[0-9]+'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          make envout >> ${GITHUB_ENV}

      - name: Prepare system
        run: |
          make prepare

      - name: Build Docker image
        run: |
          make build

      - name: Run tests
        run: |
          make test

      - name: Login Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push tag
        run: |
          make tag

