
name: Create and Test Dockerimage for silvio/docker-languagetool

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          make envout >> ${GITHUB_ENV}

      - name: show env debug
        run: |
          echo $VERSION

      - name: Prepare system
        run: |
          make prepare

      - name: Build Docker image
        run: |
          make build

      - name: Run tests
        run: |
          make test

      - name: Push tag
        run: |
          rm -f $HOME/.docker/config.json
          docker login --username=${{secrets.DOCKERHUB_USERNAME}} --password=${{secrets.DOCKERHUB_PASSWORD}} docker.io
          docker push silvio/docker-languagetool:latest
          docker push silvio/docker-languagetool:${{ env.VERSION }}

      - name: Logout Docker
        if: ${{ always() }}
        run: |
          docker logout
          rm -f $HOME/.docker/config.json

